# Yoink AI - Docker Compose Configuration
version: "3.8"
services:
  db:
    image: postgres:15
    container_name: yoink_ai_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yoink_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
